version: '3'
services:
  magento_base:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MAGENTO_PUB_KEY=${MAGENTO_PUB_KEY}
        - MAGENTO_PRIV_KEY=${MAGENTO_PRIV_KEY}
    container_name: magento_base
    restart: always
    environment:
      - WEB_ALIAS_DOMAIN=minhamaedizia.com.br
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"